global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node_exporters"
    static_configs:
      - targets:
          - server1-node:9100
          - server2-node:9100
          - server3-node:9100

  - job_name: "http_uptime"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://server1-web:3000/health
          - http://server2-web:3000/health
          - http://server3-web:3000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
